utils:
  neptune_project: adrianb3/ai-playground # neptune.ai project name
environment:
  env_path: ../../../ai_playground_build/ai_playground.exe
  time_scale: 4.0 # env time acceleration as multiplication factor over real-time
  behavior_name: CarBrain?team=0
algorithm:
  name: ppo
  params:
    ppo:
      optimizer: adam
      optimizer_params:
        adam:
          learning_rate: 0.00004
          epsilon: 0.00001
      ppo_actor_net: actor_rnn
      ppo_value_net: value_rnn
      num_epochs: 10
      discount_factor: 0.995
      gradient_clipping: 0.5
      entropy_regularization: 0.01
      importance_ratio_clipping: 0.2
      use_gae: True
      use_td_lambda_return: True

    hrl:
      optimizer: adam
      optimizer_params:
        adam:
          learning_rate: 0.005
          epsilon: 1e-5
      num_epochs: 5
train_session:
  num_env_steps: 300000
  num_parallel_envs: 4
  collect_eps_per_iter: 3
  replay_buff_capacity: 401